apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "env-${credentialname:=ecr}-credentials-sync"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "config-${credentialname:=ecr}-credentials-sync"
    kind: SecretStore
  target:
    name: "env-${credentialname:=ecr}-credentials-sync"
    deletionPolicy: "Delete"
  data:
  - secretKey: APP_MODE
    remoteRef:
      key: "infra/${infranamespaceprefix}${infracomponentname}/${credentialname:=ecr}-credentials-sync/env"
      property: APP_MODE
  - secretKey: APP_AWS_ACCOUNT_ID
    remoteRef:
      key: "infra/${infranamespaceprefix}${infracomponentname}/${credentialname:=ecr}-credentials-sync/env"
      property: APP_AWS_ACCOUNT_ID
  - secretKey: APP_AWS_REGION
    remoteRef:
      key: "infra/${infranamespaceprefix}${infracomponentname}/${credentialname:=ecr}-credentials-sync/env"
      property: APP_AWS_REGION
  - secretKey: APP_OIDC_AWS_ROLE_NAME
    remoteRef:
      key: "infra/${infranamespaceprefix}${infracomponentname}/${credentialname:=ecr}-credentials-sync/env"
      property: APP_OIDC_AWS_ROLE_NAME
  - secretKey: APP_OIDC_CLIENTID
    remoteRef:
      key: "infra/${infranamespaceprefix}${infracomponentname}/${credentialname:=ecr}-credentials-sync/env"
      property: APP_OIDC_CLIENTID
  - secretKey: APP_OIDC_PASSWORD
    remoteRef:
      key: "infra/${infranamespaceprefix}${infracomponentname}/${credentialname:=ecr}-credentials-sync/env"
      property: APP_OIDC_PASSWORD
  - secretKey: APP_OIDC_TENANT_NAME
    remoteRef:
      key: "infra/${infranamespaceprefix}${infracomponentname}/${credentialname:=ecr}-credentials-sync/env"
      property: APP_OIDC_TENANT_NAME
  - secretKey: APP_OIDC_URL
    remoteRef:
      key: "infra/${infranamespaceprefix}${infracomponentname}/${credentialname:=ecr}-credentials-sync/env"
      property: APP_OIDC_URL
  - secretKey: APP_OIDC_USERNAME
    remoteRef:
      key: "infra/${infranamespaceprefix}${infracomponentname}/${credentialname:=ecr}-credentials-sync/env"
      property: APP_OIDC_USERNAME
  - secretKey: APP_OIDC_SKIP_ECR
    remoteRef:
      key: "infra/${infranamespaceprefix}${infracomponentname}/${credentialname:=ecr}-credentials-sync/env"
      property: APP_OIDC_SKIP_ECR
