apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "config-${credentialname:=ecr}-credentials-sync"
spec:
  provider:
    vault:
      server: "${vaulturl}"
      path: "secrets"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "${clustername}"
          role: "tenant-configs-ecr-credentials-sync-reader"
          serviceAccountRef:
            name: "${credentialname:=ecr}-credentials-sync"
